version: "3"

services:
  user:
    build:
      context: ../user/
      dockerfile: Dockerfile-relation-video-user-user
    ports:
        - "8091:8091"
        - "8092:8092"
  video:
    build:
      context: ../video/
      dockerfile: Dockerfile-relation-video-user-video
    ports:
      - "8095:8095"
      - "8096:8096"
  relation:
    build:
      context: ../relation/
      dockerfile: Dockerfile-relation-video-user-relation
    ports:
      - "8093:8093"
      - "8094:8094"